ezplatform:
    system:
        site_group:
            content_view:
                full:
                    blog_post:
                        template: '@ezdesign\full\blog_post.html.twig'
                        match:
                            Identifier\ContentType: [blog_post]
                    home_page:
                        controller: ez_query::pagingQueryAction
                        template: '@ezdesign\full\home_page.html.twig'
                        match:
                            Id\Location: 2
                        params:
                            query:
                                query_type: Ride
                                limit: 4
                                assign_results_to: rides
                    ride:
                        template: '@ezdesign\full\ride.html.twig'
                        controller: App\Controller\RideController::viewRideWithLandmarksAction
                        match:
                            Identifier\ContentType: ride
                line:
                    ride:
                        template: '@ezdesign\line\rides.html.twig'
                        match:
                            Identifier\ContentType: ride
                    landmark:
                        template: '@ezdesign\line\landmark.html.twig'
                        match:
                            Identifier\ContentType: landmark

            user_registration:
                templates:
                    form: user/registration_form.html.twig
                    confirmation: user/registration_confirmation.html.twig